name: Build

on: [push, pull_request]

jobs:
  test:
    uses: DFHack/dfhack/.github/workflows/test.yml@develop
    with:
      scripts_repo: ${{ github.repository }}
      scripts_ref: ${{ github.ref }}
    secrets: inherit

  docs:
    uses: DFHack/dfhack/.github/workflows/build-linux.yml@develop
    with:
      scripts_repo: ${{ github.repository }}
      scripts_ref: ${{ github.ref }}
      artifact-name: docs
      platform-files: false
      common-files: false
      docs: true
    secrets: inherit

  lint:
    uses: DFHack/dfhack/.github/workflows/lint.yml@develop
    with:
      scripts_repo: ${{ github.repository }}
      scripts_ref: ${{ github.ref }}
    secrets: inherit
